export {default as NavbarCom} from './NavbarCom'
export {default as FeatureCom} from './FeatureCom'
export {default as ResultCom} from './ResultCom'
export {default as TailFeature} from './TailFeature'
export {default as Canvas} from './Canvas'
export {default as CanvasTail} from './CanvasTail'