export {default as FooterCon} from '../ComponentDesignCon/FooterCon'
export {default as FuselageCon} from '../ComponentDesignCon/FuselageCon'
export {default as HeaderCon} from '../ComponentDesignCon/HeaderCon'
export {default as TailCon} from '../ComponentDesignCon/TailCon'
export {default as WingCon} from '../ComponentDesignCon/WingCon'