export {default as Navbar_theo} from './TheoryBg/Navbar_theo'
export {default as Content_theo} from './TheoryBg/Content_theo'
export {default as AboutRC} from './TheoryBg/AboutRC'
export {default as Constraint_theo} from './TheoryBg/Constraint_theo'
export {default as BasicPrinciple} from './TheoryBg/BasicPrinciple'
export {default as Aerodynamics} from './TheoryBg/Aerodynamics'
export {default as Component} from './TheoryBg/Component'

export {default as ContentHome} from './HomePage/HomePageCon/ContentHome'
export {default as FooterHome} from './HomePage/HomePageCon/FooterHome'
export {default as HeaderHome} from './HomePage/HomePageCon/HeaderHome'
export {default as NavbarHome} from './HomePage/HomePageComp/NavbarHome'

export {default as Navbar_Cons} from './ConstraintDiagram/Navbar_Cons'
export {default as Input_Cons} from './ConstraintDiagram/Input_Cons'
export {default as Result_Cons} from './ConstraintDiagram/Result_Cons'
export {default as Graph_Cons} from './ConstraintDiagram/Graph_Cons'
export {default as Header_Cons} from './ConstraintDiagram/Header_Cons'
export {default as Note} from './ConstraintDiagram/Note'

export {default as FooterCon} from './ComponentDesign/ComponentDesignCon/FooterCon'
export {default as FuselageCon} from './ComponentDesign/ComponentDesignCon/FuselageCon'
export {default as HeaderCon} from './ComponentDesign/ComponentDesignCon/HeaderCon'
export {default as TailCon} from './ComponentDesign/ComponentDesignCon/TailCon'
export {default as WingCon} from './ComponentDesign/ComponentDesignCon/WingCon'
export {default as CombinationCon} from './ComponentDesign/ComponentDesignCon/CombinationCon'

export {default as NavbarCom} from './ComponentDesign/ComponentDesignComp/NavbarCom'
export {default as FeatureCom} from './ComponentDesign/ComponentDesignComp/FeatureCom'
export {default as ResultCom} from './ComponentDesign/ComponentDesignComp/ResultCom'
export {default as TailFeature} from './ComponentDesign/ComponentDesignComp/TailFeature'
export {default as Canvas} from './ComponentDesign/ComponentDesignComp/Canvas'
export {default as CanvasTail} from './ComponentDesign/ComponentDesignComp/CanvasTail'
export {default as CombinationTop} from './ComponentDesign/ComponentDesignComp/CombinationTop'
export {default as CombinationSide} from './ComponentDesign/ComponentDesignComp/CombinationSide'
export {default as CmAlpha} from './ComponentDesign/ComponentDesignComp/CmAlpha'
export {default as QuestionHover} from './ComponentDesign/ComponentDesignComp/QuestionHover'