export {default as Navbar_theo} from './pages/TheoryBg/Navbar_theo'
export {default as Content_theo} from './pages/TheoryBg/Content_theo'
export {default as AboutRC} from './pages/TheoryBg/AboutRC'
export {default as Constraint_theo} from './pages/TheoryBg/Constraint_theo'
export {default as BasicPrinciple} from './pages/TheoryBg/BasicPrinciple'
export {default as Aerodynamics} from './pages/TheoryBg/Aerodynamics'
export {default as Component} from './pages/TheoryBg/Component'

export {default as ContentHome} from './pages/HomePage/HomePageCon/ContentHome'
export {default as FooterHome} from './pages/HomePage/HomePageCon/FooterHome'
export {default as HeaderHome} from './pages/HomePage/HomePageCon/HeaderHome'
export {default as NavbarHome} from './pages/HomePage/HomePageComp/NavbarHome'

export {default as Navbar_Cons} from './pages/ConstraintDiagram/Navbar_Cons'
export {default as Input_Cons} from './pages/ConstraintDiagram/Input_Cons'
export {default as Result_Cons} from './pages/ConstraintDiagram/Result_Cons'
export {default as Graph_Cons} from './pages/ConstraintDiagram/Graph_Cons'
export {default as Header_Cons} from './pages/ConstraintDiagram/Header_Cons'
export {default as Note} from './pages/ConstraintDiagram/Note'

export {default as FooterCon} from './pages/ComponentDesign/ComponentDesignCon/FooterCon'
export {default as FuselageCon} from './pages/ComponentDesign/ComponentDesignCon/FuselageCon'
export {default as HeaderCon} from './pages/ComponentDesign/ComponentDesignCon/HeaderCon'
export {default as TailCon} from './pages/ComponentDesign/ComponentDesignCon/TailCon'
export {default as WingCon} from './pages/ComponentDesign/ComponentDesignCon/WingCon'
export {default as CombinationCon} from './pages/ComponentDesign/ComponentDesignCon/CombinationCon'

export {default as NavbarCom} from './pages/ComponentDesign/ComponentDesignComp/NavbarCom'
export {default as FeatureCom} from './pages/ComponentDesign/ComponentDesignComp/FeatureCom'
export {default as ResultCom} from './pages/ComponentDesign/ComponentDesignComp/ResultCom'
export {default as TailFeature} from './pages/ComponentDesign/ComponentDesignComp/TailFeature'
export {default as Canvas} from './pages/ComponentDesign/ComponentDesignComp/Canvas'
export {default as CanvasTail} from './pages/ComponentDesign/ComponentDesignComp/CanvasTail'
export {default as CombinationTop} from './pages/ComponentDesign/ComponentDesignComp/CombinationTop'
export {default as CombinationSide} from './pages/ComponentDesign/ComponentDesignComp/CombinationSide'
export {default as CmAlpha} from './pages/ComponentDesign/ComponentDesignComp/CmAlpha'
export {default as QuestionHover} from './pages/ComponentDesign/ComponentDesignComp/QuestionHover'