import React from 'react'
import styles from '../../styles/TheoryBg/Aerodynamics.module.css'

const Aerodynamics = () => {
  return (
<>
<div className={styles.title}><p>How do Aircrafts Fly?</p></div>
    <div className={styles.textbox}>
        <div className={styles.describtion}> 
        <p>Aerodynamics is the study of how air moves around objects, and it plays a critical role in aircraft design. The basic principle of aerodynamics is that air exerts a force on any object that moves through it. This force is called aerodynamic force and it has two components: lift and drag. <p/>
        <p>Lift is the upward force that is generated by the wings of an aircraft as they move through the air, and it's what keeps the aircraft in the air. Drag is the force that opposes the motion of the aircraft, and it's caused by the friction of the air against the aircraft's surface. </p>
        <p>To generate lift, an aircraft's wings are designed to create a difference in air pressure between the top and bottom surfaces of the wing. This pressure difference creates an upward force that lifts the aircraft. The shape and size of the wing, as well as the angle at which it's positioned relative to the airflow, are all critical factors in generating lift. Aerodynamics also plays a role in controlling the aircraft's movement through the air, such as controlling the roll, pitch, and yaw of the aircraft through the use of control surfaces, such as ailerons, elevators, and rudder.</p></p>
        </div>
    </div>
</>
  )
}

export default Aerodynamics